// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: process.proto

package process

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to check service readiness
type ReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyRequest) Reset() {
	*x = ReadyRequest{}
	mi := &file_process_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyRequest) ProtoMessage() {}

func (x *ReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_process_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyRequest.ProtoReflect.Descriptor instead.
func (*ReadyRequest) Descriptor() ([]byte, []int) {
	return file_process_proto_rawDescGZIP(), []int{0}
}

// Response indicating service readiness
type ReadyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if service is fully initialized and ready
	Ready bool `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	// Service version
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Milliseconds since service started
	UptimeMs      int64 `protobuf:"varint,3,opt,name=uptime_ms,json=uptimeMs,proto3" json:"uptime_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyResponse) Reset() {
	*x = ReadyResponse{}
	mi := &file_process_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyResponse) ProtoMessage() {}

func (x *ReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_process_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyResponse.ProtoReflect.Descriptor instead.
func (*ReadyResponse) Descriptor() ([]byte, []int) {
	return file_process_proto_rawDescGZIP(), []int{1}
}

func (x *ReadyResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *ReadyResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ReadyResponse) GetUptimeMs() int64 {
	if x != nil {
		return x.UptimeMs
	}
	return 0
}

type StartProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProcessRequest) Reset() {
	*x = StartProcessRequest{}
	mi := &file_process_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessRequest) ProtoMessage() {}

func (x *StartProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_process_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessRequest.ProtoReflect.Descriptor instead.
func (*StartProcessRequest) Descriptor() ([]byte, []int) {
	return file_process_proto_rawDescGZIP(), []int{2}
}

type StartProcessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// PID of started process
	Pid           int32 `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartProcessResponse) Reset() {
	*x = StartProcessResponse{}
	mi := &file_process_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartProcessResponse) ProtoMessage() {}

func (x *StartProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_process_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartProcessResponse.ProtoReflect.Descriptor instead.
func (*StartProcessResponse) Descriptor() ([]byte, []int) {
	return file_process_proto_rawDescGZIP(), []int{3}
}

func (x *StartProcessResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartProcessResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StartProcessResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type GetProcessStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProcessStatusRequest) Reset() {
	*x = GetProcessStatusRequest{}
	mi := &file_process_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessStatusRequest) ProtoMessage() {}

func (x *GetProcessStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_process_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessStatusRequest.ProtoReflect.Descriptor instead.
func (*GetProcessStatusRequest) Descriptor() ([]byte, []int) {
	return file_process_proto_rawDescGZIP(), []int{4}
}

type GetProcessStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Process state: "waiting", "running", "exited"
	State string `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	// PID if running
	Pid int32 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	// Exit code if exited
	ExitCode      int32 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProcessStatusResponse) Reset() {
	*x = GetProcessStatusResponse{}
	mi := &file_process_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessStatusResponse) ProtoMessage() {}

func (x *GetProcessStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_process_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessStatusResponse.ProtoReflect.Descriptor instead.
func (*GetProcessStatusResponse) Descriptor() ([]byte, []int) {
	return file_process_proto_rawDescGZIP(), []int{5}
}

func (x *GetProcessStatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetProcessStatusResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *GetProcessStatusResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type ListProcessesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional ps arguments (e.g., "-ef", "-aux")
	// If empty, defaults to "-ef"
	PsArgs        string `protobuf:"bytes,1,opt,name=ps_args,json=psArgs,proto3" json:"ps_args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProcessesRequest) Reset() {
	*x = ListProcessesRequest{}
	mi := &file_process_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProcessesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcessesRequest) ProtoMessage() {}

func (x *ListProcessesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_process_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcessesRequest.ProtoReflect.Descriptor instead.
func (*ListProcessesRequest) Descriptor() ([]byte, []int) {
	return file_process_proto_rawDescGZIP(), []int{6}
}

func (x *ListProcessesRequest) GetPsArgs() string {
	if x != nil {
		return x.PsArgs
	}
	return ""
}

type ListProcessesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Column titles (e.g., ["UID", "PID", "PPID", "C", "STIME", "TTY", "TIME", "CMD"])
	Titles []string `protobuf:"bytes,1,rep,name=titles,proto3" json:"titles,omitempty"`
	// Each process is an array of values corresponding to the titles
	// For example: [["root", "1", "0", "0", "12:00", "?", "00:00:00", "/bin/sh"]]
	Processes     []*ProcessInfo `protobuf:"bytes,2,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProcessesResponse) Reset() {
	*x = ListProcessesResponse{}
	mi := &file_process_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProcessesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcessesResponse) ProtoMessage() {}

func (x *ListProcessesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_process_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcessesResponse.ProtoReflect.Descriptor instead.
func (*ListProcessesResponse) Descriptor() ([]byte, []int) {
	return file_process_proto_rawDescGZIP(), []int{7}
}

func (x *ListProcessesResponse) GetTitles() []string {
	if x != nil {
		return x.Titles
	}
	return nil
}

func (x *ListProcessesResponse) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

type ProcessInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Values for this process, corresponding to titles in ListProcessesResponse
	Values        []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_process_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_process_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_process_proto_rawDescGZIP(), []int{8}
}

func (x *ProcessInfo) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_process_proto protoreflect.FileDescriptor

const file_process_proto_rawDesc = "" +
	"\n" +
	"\rprocess.proto\x12\x0farca.process.v1\"\x0e\n" +
	"\fReadyRequest\"\\\n" +
	"\rReadyResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1b\n" +
	"\tuptime_ms\x18\x03 \x01(\x03R\buptimeMs\"\x15\n" +
	"\x13StartProcessRequest\"g\n" +
	"\x14StartProcessResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\"\x19\n" +
	"\x17GetProcessStatusRequest\"_\n" +
	"\x18GetProcessStatusResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\"/\n" +
	"\x14ListProcessesRequest\x12\x17\n" +
	"\aps_args\x18\x01 \x01(\tR\x06psArgs\"k\n" +
	"\x15ListProcessesResponse\x12\x16\n" +
	"\x06titles\x18\x01 \x03(\tR\x06titles\x12:\n" +
	"\tprocesses\x18\x02 \x03(\v2\x1c.arca.process.v1.ProcessInfoR\tprocesses\"%\n" +
	"\vProcessInfo\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values2\xfe\x02\n" +
	"\x0eProcessService\x12F\n" +
	"\x05Ready\x12\x1d.arca.process.v1.ReadyRequest\x1a\x1e.arca.process.v1.ReadyResponse\x12[\n" +
	"\fStartProcess\x12$.arca.process.v1.StartProcessRequest\x1a%.arca.process.v1.StartProcessResponse\x12g\n" +
	"\x10GetProcessStatus\x12(.arca.process.v1.GetProcessStatusRequest\x1a).arca.process.v1.GetProcessStatusResponse\x12^\n" +
	"\rListProcesses\x12%.arca.process.v1.ListProcessesRequest\x1a&.arca.process.v1.ListProcessesResponseB4Z2github.com/vas-solutus/arca-services/proto/processb\x06proto3"

var (
	file_process_proto_rawDescOnce sync.Once
	file_process_proto_rawDescData []byte
)

func file_process_proto_rawDescGZIP() []byte {
	file_process_proto_rawDescOnce.Do(func() {
		file_process_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_process_proto_rawDesc), len(file_process_proto_rawDesc)))
	})
	return file_process_proto_rawDescData
}

var file_process_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_process_proto_goTypes = []any{
	(*ReadyRequest)(nil),             // 0: arca.process.v1.ReadyRequest
	(*ReadyResponse)(nil),            // 1: arca.process.v1.ReadyResponse
	(*StartProcessRequest)(nil),      // 2: arca.process.v1.StartProcessRequest
	(*StartProcessResponse)(nil),     // 3: arca.process.v1.StartProcessResponse
	(*GetProcessStatusRequest)(nil),  // 4: arca.process.v1.GetProcessStatusRequest
	(*GetProcessStatusResponse)(nil), // 5: arca.process.v1.GetProcessStatusResponse
	(*ListProcessesRequest)(nil),     // 6: arca.process.v1.ListProcessesRequest
	(*ListProcessesResponse)(nil),    // 7: arca.process.v1.ListProcessesResponse
	(*ProcessInfo)(nil),              // 8: arca.process.v1.ProcessInfo
}
var file_process_proto_depIdxs = []int32{
	8, // 0: arca.process.v1.ListProcessesResponse.processes:type_name -> arca.process.v1.ProcessInfo
	0, // 1: arca.process.v1.ProcessService.Ready:input_type -> arca.process.v1.ReadyRequest
	2, // 2: arca.process.v1.ProcessService.StartProcess:input_type -> arca.process.v1.StartProcessRequest
	4, // 3: arca.process.v1.ProcessService.GetProcessStatus:input_type -> arca.process.v1.GetProcessStatusRequest
	6, // 4: arca.process.v1.ProcessService.ListProcesses:input_type -> arca.process.v1.ListProcessesRequest
	1, // 5: arca.process.v1.ProcessService.Ready:output_type -> arca.process.v1.ReadyResponse
	3, // 6: arca.process.v1.ProcessService.StartProcess:output_type -> arca.process.v1.StartProcessResponse
	5, // 7: arca.process.v1.ProcessService.GetProcessStatus:output_type -> arca.process.v1.GetProcessStatusResponse
	7, // 8: arca.process.v1.ProcessService.ListProcesses:output_type -> arca.process.v1.ListProcessesResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_process_proto_init() }
func file_process_proto_init() {
	if File_process_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_process_proto_rawDesc), len(file_process_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_process_proto_goTypes,
		DependencyIndexes: file_process_proto_depIdxs,
		MessageInfos:      file_process_proto_msgTypes,
	}.Build()
	File_process_proto = out.File
	file_process_proto_goTypes = nil
	file_process_proto_depIdxs = nil
}
