// Arca Container Filesystem Service Protocol
// gRPC API for container filesystem operations
//
// This service runs on vsock port 51821 in each container's Linux VM
// and provides filesystem operations including:
// - Filesystem sync (flush buffers)
// - Archive operations (tar creation/extraction for buildx)
// - OverlayFS upperdir enumeration (for docker diff)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: filesystem.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to sync filesystem (flush all cached writes)
type SyncFilesystemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncFilesystemRequest) Reset() {
	*x = SyncFilesystemRequest{}
	mi := &file_filesystem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFilesystemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFilesystemRequest) ProtoMessage() {}

func (x *SyncFilesystemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFilesystemRequest.ProtoReflect.Descriptor instead.
func (*SyncFilesystemRequest) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{0}
}

type SyncFilesystemResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncFilesystemResponse) Reset() {
	*x = SyncFilesystemResponse{}
	mi := &file_filesystem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFilesystemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFilesystemResponse) ProtoMessage() {}

func (x *SyncFilesystemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFilesystemResponse.ProtoReflect.Descriptor instead.
func (*SyncFilesystemResponse) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{1}
}

func (x *SyncFilesystemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncFilesystemResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Request to enumerate OverlayFS upperdir for container diff
type EnumerateUpperdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumerateUpperdirRequest) Reset() {
	*x = EnumerateUpperdirRequest{}
	mi := &file_filesystem_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumerateUpperdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumerateUpperdirRequest) ProtoMessage() {}

func (x *EnumerateUpperdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumerateUpperdirRequest.ProtoReflect.Descriptor instead.
func (*EnumerateUpperdirRequest) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{2}
}

type EnumerateUpperdirResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Files and directories in upperdir
	Entries       []*UpperdirEntry `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumerateUpperdirResponse) Reset() {
	*x = EnumerateUpperdirResponse{}
	mi := &file_filesystem_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumerateUpperdirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumerateUpperdirResponse) ProtoMessage() {}

func (x *EnumerateUpperdirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumerateUpperdirResponse.ProtoReflect.Descriptor instead.
func (*EnumerateUpperdirResponse) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{3}
}

func (x *EnumerateUpperdirResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EnumerateUpperdirResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *EnumerateUpperdirResponse) GetEntries() []*UpperdirEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Represents a file, directory, or whiteout in the OverlayFS upperdir
type UpperdirEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path relative to container root (e.g., "/etc/hosts", "/tmp/myfile")
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Entry type: "file", "dir", "symlink", "whiteout"
	// "whiteout" indicates a deleted file (character device 0/0 in upperdir)
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// File size in bytes (0 for directories and whiteouts)
	Size int64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// Modification time (Unix timestamp seconds)
	Mtime int64 `protobuf:"varint,4,opt,name=mtime,proto3" json:"mtime,omitempty"`
	// File mode/permissions (Unix mode bits)
	Mode          uint32 `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpperdirEntry) Reset() {
	*x = UpperdirEntry{}
	mi := &file_filesystem_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpperdirEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpperdirEntry) ProtoMessage() {}

func (x *UpperdirEntry) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpperdirEntry.ProtoReflect.Descriptor instead.
func (*UpperdirEntry) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{4}
}

func (x *UpperdirEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UpperdirEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpperdirEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UpperdirEntry) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *UpperdirEntry) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

// Request to read archive from filesystem path
type ReadArchiveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container ID (for resolving /run/container/{id}/rootfs path)
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// Path to file or directory to archive (e.g., "/tmp/myfile.txt" or "/etc")
	Path          string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadArchiveRequest) Reset() {
	*x = ReadArchiveRequest{}
	mi := &file_filesystem_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadArchiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadArchiveRequest) ProtoMessage() {}

func (x *ReadArchiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadArchiveRequest.ProtoReflect.Descriptor instead.
func (*ReadArchiveRequest) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{5}
}

func (x *ReadArchiveRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ReadArchiveRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadArchiveResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Tar archive data (gzip compressed)
	TarData []byte `protobuf:"bytes,3,opt,name=tar_data,json=tarData,proto3" json:"tar_data,omitempty"`
	// File stat information (for X-Docker-Container-Path-Stat header)
	Stat          *PathStat `protobuf:"bytes,4,opt,name=stat,proto3" json:"stat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadArchiveResponse) Reset() {
	*x = ReadArchiveResponse{}
	mi := &file_filesystem_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadArchiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadArchiveResponse) ProtoMessage() {}

func (x *ReadArchiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadArchiveResponse.ProtoReflect.Descriptor instead.
func (*ReadArchiveResponse) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{6}
}

func (x *ReadArchiveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReadArchiveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReadArchiveResponse) GetTarData() []byte {
	if x != nil {
		return x.TarData
	}
	return nil
}

func (x *ReadArchiveResponse) GetStat() *PathStat {
	if x != nil {
		return x.Stat
	}
	return nil
}

// File stat information for archived paths
type PathStat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// File or directory name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// File size in bytes
	Size int64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// File mode/permissions (os.FileMode as uint32)
	Mode uint32 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	// Modification time (RFC3339 format: "2006-01-02T15:04:05Z07:00")
	Mtime string `protobuf:"bytes,4,opt,name=mtime,proto3" json:"mtime,omitempty"`
	// Symbolic link target (empty if not a symlink)
	LinkTarget    string `protobuf:"bytes,5,opt,name=link_target,json=linkTarget,proto3" json:"link_target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathStat) Reset() {
	*x = PathStat{}
	mi := &file_filesystem_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathStat) ProtoMessage() {}

func (x *PathStat) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathStat.ProtoReflect.Descriptor instead.
func (*PathStat) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{7}
}

func (x *PathStat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PathStat) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PathStat) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *PathStat) GetMtime() string {
	if x != nil {
		return x.Mtime
	}
	return ""
}

func (x *PathStat) GetLinkTarget() string {
	if x != nil {
		return x.LinkTarget
	}
	return ""
}

// Request to write archive to filesystem path
type WriteArchiveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container ID (for resolving /run/container/{id}/rootfs path)
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// Destination path where archive should be extracted (e.g., "/tmp")
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Tar archive data to extract
	TarData       []byte `protobuf:"bytes,3,opt,name=tar_data,json=tarData,proto3" json:"tar_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteArchiveRequest) Reset() {
	*x = WriteArchiveRequest{}
	mi := &file_filesystem_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteArchiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteArchiveRequest) ProtoMessage() {}

func (x *WriteArchiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteArchiveRequest.ProtoReflect.Descriptor instead.
func (*WriteArchiveRequest) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{8}
}

func (x *WriteArchiveRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *WriteArchiveRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteArchiveRequest) GetTarData() []byte {
	if x != nil {
		return x.TarData
	}
	return nil
}

type WriteArchiveResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteArchiveResponse) Reset() {
	*x = WriteArchiveResponse{}
	mi := &file_filesystem_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteArchiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteArchiveResponse) ProtoMessage() {}

func (x *WriteArchiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteArchiveResponse.ProtoReflect.Descriptor instead.
func (*WriteArchiveResponse) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{9}
}

func (x *WriteArchiveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WriteArchiveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Request to create a bind mount inside the container
type CreateBindMountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container ID (for resolving /run/container/{id}/rootfs path)
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// Source path inside VM (absolute path, e.g., "/mnt/arca-file-mounts/abc123/myfile.txt")
	// Can be a file or directory
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// Target path relative to container root (e.g., "/test.txt" or "/app/config.yaml")
	// Will be resolved to /run/container/{container_id}/rootfs{target}
	Target string `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	// Read-only mount (default: false for read-write)
	ReadOnly      bool `protobuf:"varint,4,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBindMountRequest) Reset() {
	*x = CreateBindMountRequest{}
	mi := &file_filesystem_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBindMountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBindMountRequest) ProtoMessage() {}

func (x *CreateBindMountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBindMountRequest.ProtoReflect.Descriptor instead.
func (*CreateBindMountRequest) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{10}
}

func (x *CreateBindMountRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *CreateBindMountRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CreateBindMountRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *CreateBindMountRequest) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type CreateBindMountResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBindMountResponse) Reset() {
	*x = CreateBindMountResponse{}
	mi := &file_filesystem_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBindMountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBindMountResponse) ProtoMessage() {}

func (x *CreateBindMountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBindMountResponse.ProtoReflect.Descriptor instead.
func (*CreateBindMountResponse) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{11}
}

func (x *CreateBindMountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateBindMountResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_filesystem_proto protoreflect.FileDescriptor

const file_filesystem_proto_rawDesc = "" +
	"\n" +
	"\x10filesystem.proto\x12\x12arca.filesystem.v1\"\x17\n" +
	"\x15SyncFilesystemRequest\"H\n" +
	"\x16SyncFilesystemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x1a\n" +
	"\x18EnumerateUpperdirRequest\"\x88\x01\n" +
	"\x19EnumerateUpperdirResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12;\n" +
	"\aentries\x18\x03 \x03(\v2!.arca.filesystem.v1.UpperdirEntryR\aentries\"u\n" +
	"\rUpperdirEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x14\n" +
	"\x05mtime\x18\x04 \x01(\x03R\x05mtime\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\rR\x04mode\"K\n" +
	"\x12ReadArchiveRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x92\x01\n" +
	"\x13ReadArchiveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x19\n" +
	"\btar_data\x18\x03 \x01(\fR\atarData\x120\n" +
	"\x04stat\x18\x04 \x01(\v2\x1c.arca.filesystem.v1.PathStatR\x04stat\"}\n" +
	"\bPathStat\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\x12\x14\n" +
	"\x05mtime\x18\x04 \x01(\tR\x05mtime\x12\x1f\n" +
	"\vlink_target\x18\x05 \x01(\tR\n" +
	"linkTarget\"g\n" +
	"\x13WriteArchiveRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x19\n" +
	"\btar_data\x18\x03 \x01(\fR\atarData\"F\n" +
	"\x14WriteArchiveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x88\x01\n" +
	"\x16CreateBindMountRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x1b\n" +
	"\tread_only\x18\x04 \x01(\bR\breadOnly\"I\n" +
	"\x17CreateBindMountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\x9d\x04\n" +
	"\x11FilesystemService\x12g\n" +
	"\x0eSyncFilesystem\x12).arca.filesystem.v1.SyncFilesystemRequest\x1a*.arca.filesystem.v1.SyncFilesystemResponse\x12p\n" +
	"\x11EnumerateUpperdir\x12,.arca.filesystem.v1.EnumerateUpperdirRequest\x1a-.arca.filesystem.v1.EnumerateUpperdirResponse\x12^\n" +
	"\vReadArchive\x12&.arca.filesystem.v1.ReadArchiveRequest\x1a'.arca.filesystem.v1.ReadArchiveResponse\x12a\n" +
	"\fWriteArchive\x12'.arca.filesystem.v1.WriteArchiveRequest\x1a(.arca.filesystem.v1.WriteArchiveResponse\x12j\n" +
	"\x0fCreateBindMount\x12*.arca.filesystem.v1.CreateBindMountRequest\x1a+.arca.filesystem.v1.CreateBindMountResponseB6Z4github.com/vas-solutus/arca-filesystem-service/protob\x06proto3"

var (
	file_filesystem_proto_rawDescOnce sync.Once
	file_filesystem_proto_rawDescData []byte
)

func file_filesystem_proto_rawDescGZIP() []byte {
	file_filesystem_proto_rawDescOnce.Do(func() {
		file_filesystem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_filesystem_proto_rawDesc), len(file_filesystem_proto_rawDesc)))
	})
	return file_filesystem_proto_rawDescData
}

var file_filesystem_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_filesystem_proto_goTypes = []any{
	(*SyncFilesystemRequest)(nil),     // 0: arca.filesystem.v1.SyncFilesystemRequest
	(*SyncFilesystemResponse)(nil),    // 1: arca.filesystem.v1.SyncFilesystemResponse
	(*EnumerateUpperdirRequest)(nil),  // 2: arca.filesystem.v1.EnumerateUpperdirRequest
	(*EnumerateUpperdirResponse)(nil), // 3: arca.filesystem.v1.EnumerateUpperdirResponse
	(*UpperdirEntry)(nil),             // 4: arca.filesystem.v1.UpperdirEntry
	(*ReadArchiveRequest)(nil),        // 5: arca.filesystem.v1.ReadArchiveRequest
	(*ReadArchiveResponse)(nil),       // 6: arca.filesystem.v1.ReadArchiveResponse
	(*PathStat)(nil),                  // 7: arca.filesystem.v1.PathStat
	(*WriteArchiveRequest)(nil),       // 8: arca.filesystem.v1.WriteArchiveRequest
	(*WriteArchiveResponse)(nil),      // 9: arca.filesystem.v1.WriteArchiveResponse
	(*CreateBindMountRequest)(nil),    // 10: arca.filesystem.v1.CreateBindMountRequest
	(*CreateBindMountResponse)(nil),   // 11: arca.filesystem.v1.CreateBindMountResponse
}
var file_filesystem_proto_depIdxs = []int32{
	4,  // 0: arca.filesystem.v1.EnumerateUpperdirResponse.entries:type_name -> arca.filesystem.v1.UpperdirEntry
	7,  // 1: arca.filesystem.v1.ReadArchiveResponse.stat:type_name -> arca.filesystem.v1.PathStat
	0,  // 2: arca.filesystem.v1.FilesystemService.SyncFilesystem:input_type -> arca.filesystem.v1.SyncFilesystemRequest
	2,  // 3: arca.filesystem.v1.FilesystemService.EnumerateUpperdir:input_type -> arca.filesystem.v1.EnumerateUpperdirRequest
	5,  // 4: arca.filesystem.v1.FilesystemService.ReadArchive:input_type -> arca.filesystem.v1.ReadArchiveRequest
	8,  // 5: arca.filesystem.v1.FilesystemService.WriteArchive:input_type -> arca.filesystem.v1.WriteArchiveRequest
	10, // 6: arca.filesystem.v1.FilesystemService.CreateBindMount:input_type -> arca.filesystem.v1.CreateBindMountRequest
	1,  // 7: arca.filesystem.v1.FilesystemService.SyncFilesystem:output_type -> arca.filesystem.v1.SyncFilesystemResponse
	3,  // 8: arca.filesystem.v1.FilesystemService.EnumerateUpperdir:output_type -> arca.filesystem.v1.EnumerateUpperdirResponse
	6,  // 9: arca.filesystem.v1.FilesystemService.ReadArchive:output_type -> arca.filesystem.v1.ReadArchiveResponse
	9,  // 10: arca.filesystem.v1.FilesystemService.WriteArchive:output_type -> arca.filesystem.v1.WriteArchiveResponse
	11, // 11: arca.filesystem.v1.FilesystemService.CreateBindMount:output_type -> arca.filesystem.v1.CreateBindMountResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_filesystem_proto_init() }
func file_filesystem_proto_init() {
	if File_filesystem_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_filesystem_proto_rawDesc), len(file_filesystem_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_filesystem_proto_goTypes,
		DependencyIndexes: file_filesystem_proto_depIdxs,
		MessageInfos:      file_filesystem_proto_msgTypes,
	}.Build()
	File_filesystem_proto = out.File
	file_filesystem_proto_goTypes = nil
	file_filesystem_proto_depIdxs = nil
}
