// Arca WireGuard Network Service Protocol
// gRPC API for WireGuard-based container networking

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: wireguard.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WireGuardService_AddNetwork_FullMethodName       = "/arca.wireguard.v1.WireGuardService/AddNetwork"
	WireGuardService_RemoveNetwork_FullMethodName    = "/arca.wireguard.v1.WireGuardService/RemoveNetwork"
	WireGuardService_AddPeer_FullMethodName          = "/arca.wireguard.v1.WireGuardService/AddPeer"
	WireGuardService_RemovePeer_FullMethodName       = "/arca.wireguard.v1.WireGuardService/RemovePeer"
	WireGuardService_GetStatus_FullMethodName        = "/arca.wireguard.v1.WireGuardService/GetStatus"
	WireGuardService_GetVmnetEndpoint_FullMethodName = "/arca.wireguard.v1.WireGuardService/GetVmnetEndpoint"
	WireGuardService_PublishPort_FullMethodName      = "/arca.wireguard.v1.WireGuardService/PublishPort"
	WireGuardService_UnpublishPort_FullMethodName    = "/arca.wireguard.v1.WireGuardService/UnpublishPort"
	WireGuardService_DumpNftables_FullMethodName     = "/arca.wireguard.v1.WireGuardService/DumpNftables"
)

// WireGuardServiceClient is the client API for WireGuardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WireGuardService manages WireGuard hubs and peer connections for container networking
// Runs on vsock port 51820 in container's init system namespace
type WireGuardServiceClient interface {
	// Add a network to this container (creates wgN interface + veth pair, renames to ethN)
	// For multi-network: network_index=0 → wg0/eth0, network_index=1 → wg1/eth1, etc.
	AddNetwork(ctx context.Context, in *AddNetworkRequest, opts ...grpc.CallOption) (*AddNetworkResponse, error)
	// Remove a network from this container (deletes wgN interface and ethN)
	RemoveNetwork(ctx context.Context, in *RemoveNetworkRequest, opts ...grpc.CallOption) (*RemoveNetworkResponse, error)
	// Add a peer to a WireGuard interface (for full mesh networking)
	AddPeer(ctx context.Context, in *AddPeerRequest, opts ...grpc.CallOption) (*AddPeerResponse, error)
	// Remove a peer from a WireGuard interface
	RemovePeer(ctx context.Context, in *RemovePeerRequest, opts ...grpc.CallOption) (*RemovePeerResponse, error)
	// Get WireGuard status and statistics
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// Get container's vmnet endpoint (eth0 IP:port) for peer configuration
	GetVmnetEndpoint(ctx context.Context, in *GetVmnetEndpointRequest, opts ...grpc.CallOption) (*GetVmnetEndpointResponse, error)
	// Publish a port (create DNAT rule for host port → container port)
	PublishPort(ctx context.Context, in *PublishPortRequest, opts ...grpc.CallOption) (*PublishPortResponse, error)
	// Unpublish a port (remove DNAT rule)
	UnpublishPort(ctx context.Context, in *UnpublishPortRequest, opts ...grpc.CallOption) (*UnpublishPortResponse, error)
	// Dump nftables state for debugging (returns full ruleset with counters)
	DumpNftables(ctx context.Context, in *DumpNftablesRequest, opts ...grpc.CallOption) (*DumpNftablesResponse, error)
}

type wireGuardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWireGuardServiceClient(cc grpc.ClientConnInterface) WireGuardServiceClient {
	return &wireGuardServiceClient{cc}
}

func (c *wireGuardServiceClient) AddNetwork(ctx context.Context, in *AddNetworkRequest, opts ...grpc.CallOption) (*AddNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddNetworkResponse)
	err := c.cc.Invoke(ctx, WireGuardService_AddNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuardServiceClient) RemoveNetwork(ctx context.Context, in *RemoveNetworkRequest, opts ...grpc.CallOption) (*RemoveNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveNetworkResponse)
	err := c.cc.Invoke(ctx, WireGuardService_RemoveNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuardServiceClient) AddPeer(ctx context.Context, in *AddPeerRequest, opts ...grpc.CallOption) (*AddPeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddPeerResponse)
	err := c.cc.Invoke(ctx, WireGuardService_AddPeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuardServiceClient) RemovePeer(ctx context.Context, in *RemovePeerRequest, opts ...grpc.CallOption) (*RemovePeerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemovePeerResponse)
	err := c.cc.Invoke(ctx, WireGuardService_RemovePeer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuardServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, WireGuardService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuardServiceClient) GetVmnetEndpoint(ctx context.Context, in *GetVmnetEndpointRequest, opts ...grpc.CallOption) (*GetVmnetEndpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVmnetEndpointResponse)
	err := c.cc.Invoke(ctx, WireGuardService_GetVmnetEndpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuardServiceClient) PublishPort(ctx context.Context, in *PublishPortRequest, opts ...grpc.CallOption) (*PublishPortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishPortResponse)
	err := c.cc.Invoke(ctx, WireGuardService_PublishPort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuardServiceClient) UnpublishPort(ctx context.Context, in *UnpublishPortRequest, opts ...grpc.CallOption) (*UnpublishPortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnpublishPortResponse)
	err := c.cc.Invoke(ctx, WireGuardService_UnpublishPort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuardServiceClient) DumpNftables(ctx context.Context, in *DumpNftablesRequest, opts ...grpc.CallOption) (*DumpNftablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DumpNftablesResponse)
	err := c.cc.Invoke(ctx, WireGuardService_DumpNftables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WireGuardServiceServer is the server API for WireGuardService service.
// All implementations must embed UnimplementedWireGuardServiceServer
// for forward compatibility.
//
// WireGuardService manages WireGuard hubs and peer connections for container networking
// Runs on vsock port 51820 in container's init system namespace
type WireGuardServiceServer interface {
	// Add a network to this container (creates wgN interface + veth pair, renames to ethN)
	// For multi-network: network_index=0 → wg0/eth0, network_index=1 → wg1/eth1, etc.
	AddNetwork(context.Context, *AddNetworkRequest) (*AddNetworkResponse, error)
	// Remove a network from this container (deletes wgN interface and ethN)
	RemoveNetwork(context.Context, *RemoveNetworkRequest) (*RemoveNetworkResponse, error)
	// Add a peer to a WireGuard interface (for full mesh networking)
	AddPeer(context.Context, *AddPeerRequest) (*AddPeerResponse, error)
	// Remove a peer from a WireGuard interface
	RemovePeer(context.Context, *RemovePeerRequest) (*RemovePeerResponse, error)
	// Get WireGuard status and statistics
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// Get container's vmnet endpoint (eth0 IP:port) for peer configuration
	GetVmnetEndpoint(context.Context, *GetVmnetEndpointRequest) (*GetVmnetEndpointResponse, error)
	// Publish a port (create DNAT rule for host port → container port)
	PublishPort(context.Context, *PublishPortRequest) (*PublishPortResponse, error)
	// Unpublish a port (remove DNAT rule)
	UnpublishPort(context.Context, *UnpublishPortRequest) (*UnpublishPortResponse, error)
	// Dump nftables state for debugging (returns full ruleset with counters)
	DumpNftables(context.Context, *DumpNftablesRequest) (*DumpNftablesResponse, error)
	mustEmbedUnimplementedWireGuardServiceServer()
}

// UnimplementedWireGuardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWireGuardServiceServer struct{}

func (UnimplementedWireGuardServiceServer) AddNetwork(context.Context, *AddNetworkRequest) (*AddNetworkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNetwork not implemented")
}
func (UnimplementedWireGuardServiceServer) RemoveNetwork(context.Context, *RemoveNetworkRequest) (*RemoveNetworkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveNetwork not implemented")
}
func (UnimplementedWireGuardServiceServer) AddPeer(context.Context, *AddPeerRequest) (*AddPeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPeer not implemented")
}
func (UnimplementedWireGuardServiceServer) RemovePeer(context.Context, *RemovePeerRequest) (*RemovePeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePeer not implemented")
}
func (UnimplementedWireGuardServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedWireGuardServiceServer) GetVmnetEndpoint(context.Context, *GetVmnetEndpointRequest) (*GetVmnetEndpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVmnetEndpoint not implemented")
}
func (UnimplementedWireGuardServiceServer) PublishPort(context.Context, *PublishPortRequest) (*PublishPortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishPort not implemented")
}
func (UnimplementedWireGuardServiceServer) UnpublishPort(context.Context, *UnpublishPortRequest) (*UnpublishPortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnpublishPort not implemented")
}
func (UnimplementedWireGuardServiceServer) DumpNftables(context.Context, *DumpNftablesRequest) (*DumpNftablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DumpNftables not implemented")
}
func (UnimplementedWireGuardServiceServer) mustEmbedUnimplementedWireGuardServiceServer() {}
func (UnimplementedWireGuardServiceServer) testEmbeddedByValue()                          {}

// UnsafeWireGuardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WireGuardServiceServer will
// result in compilation errors.
type UnsafeWireGuardServiceServer interface {
	mustEmbedUnimplementedWireGuardServiceServer()
}

func RegisterWireGuardServiceServer(s grpc.ServiceRegistrar, srv WireGuardServiceServer) {
	// If the following call pancis, it indicates UnimplementedWireGuardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WireGuardService_ServiceDesc, srv)
}

func _WireGuardService_AddNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuardServiceServer).AddNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuardService_AddNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuardServiceServer).AddNetwork(ctx, req.(*AddNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuardService_RemoveNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuardServiceServer).RemoveNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuardService_RemoveNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuardServiceServer).RemoveNetwork(ctx, req.(*RemoveNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuardService_AddPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuardServiceServer).AddPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuardService_AddPeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuardServiceServer).AddPeer(ctx, req.(*AddPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuardService_RemovePeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuardServiceServer).RemovePeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuardService_RemovePeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuardServiceServer).RemovePeer(ctx, req.(*RemovePeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuardService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuardServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuardService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuardServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuardService_GetVmnetEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVmnetEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuardServiceServer).GetVmnetEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuardService_GetVmnetEndpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuardServiceServer).GetVmnetEndpoint(ctx, req.(*GetVmnetEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuardService_PublishPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishPortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuardServiceServer).PublishPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuardService_PublishPort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuardServiceServer).PublishPort(ctx, req.(*PublishPortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuardService_UnpublishPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnpublishPortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuardServiceServer).UnpublishPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuardService_UnpublishPort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuardServiceServer).UnpublishPort(ctx, req.(*UnpublishPortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuardService_DumpNftables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DumpNftablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuardServiceServer).DumpNftables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuardService_DumpNftables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuardServiceServer).DumpNftables(ctx, req.(*DumpNftablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WireGuardService_ServiceDesc is the grpc.ServiceDesc for WireGuardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WireGuardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arca.wireguard.v1.WireGuardService",
	HandlerType: (*WireGuardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddNetwork",
			Handler:    _WireGuardService_AddNetwork_Handler,
		},
		{
			MethodName: "RemoveNetwork",
			Handler:    _WireGuardService_RemoveNetwork_Handler,
		},
		{
			MethodName: "AddPeer",
			Handler:    _WireGuardService_AddPeer_Handler,
		},
		{
			MethodName: "RemovePeer",
			Handler:    _WireGuardService_RemovePeer_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _WireGuardService_GetStatus_Handler,
		},
		{
			MethodName: "GetVmnetEndpoint",
			Handler:    _WireGuardService_GetVmnetEndpoint_Handler,
		},
		{
			MethodName: "PublishPort",
			Handler:    _WireGuardService_PublishPort_Handler,
		},
		{
			MethodName: "UnpublishPort",
			Handler:    _WireGuardService_UnpublishPort_Handler,
		},
		{
			MethodName: "DumpNftables",
			Handler:    _WireGuardService_DumpNftables_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wireguard.proto",
}
