// Arca WireGuard Network Service Protocol
// gRPC API for WireGuard-based container networking

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: wireguard.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to add a network to the container
type AddNetworkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Network ID (Docker network ID)
	NetworkId string `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	// Network index (0 for first network → wg0/eth0, 1 for second → wg1/eth1, etc.)
	NetworkIndex uint32 `protobuf:"varint,2,opt,name=network_index,json=networkIndex,proto3" json:"network_index,omitempty"`
	// Private key for this container's WireGuard interface (Base64-encoded Curve25519 key)
	// Each wgN interface gets its own private key
	PrivateKey string `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	// Listen port for WireGuard (51820 + network_index)
	ListenPort uint32 `protobuf:"varint,4,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	// Peer endpoint (peer's vmnet IP address, e.g., "192.168.65.5:51820")
	PeerEndpoint string `protobuf:"bytes,5,opt,name=peer_endpoint,json=peerEndpoint,proto3" json:"peer_endpoint,omitempty"`
	// Peer's public key (Base64-encoded)
	PeerPublicKey string `protobuf:"bytes,6,opt,name=peer_public_key,json=peerPublicKey,proto3" json:"peer_public_key,omitempty"`
	// IP address for this container on this network
	IpAddress string `protobuf:"bytes,7,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// Network CIDR for routing (e.g., "172.18.0.0/16")
	NetworkCidr string `protobuf:"bytes,8,opt,name=network_cidr,json=networkCidr,proto3" json:"network_cidr,omitempty"`
	// Gateway IP for this network (e.g., "172.18.0.1")
	Gateway string `protobuf:"bytes,9,opt,name=gateway,proto3" json:"gateway,omitempty"`
	// Host IP address for host.docker.internal DNS resolution (e.g., "192.168.2.100")
	// This is the macOS host's LAN IP, allowing containers to reach host services
	HostIp        string `protobuf:"bytes,10,opt,name=host_ip,json=hostIp,proto3" json:"host_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNetworkRequest) Reset() {
	*x = AddNetworkRequest{}
	mi := &file_wireguard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNetworkRequest) ProtoMessage() {}

func (x *AddNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wireguard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNetworkRequest.ProtoReflect.Descriptor instead.
func (*AddNetworkRequest) Descriptor() ([]byte, []int) {
	return file_wireguard_proto_rawDescGZIP(), []int{0}
}

func (x *AddNetworkRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *AddNetworkRequest) GetNetworkIndex() uint32 {
	if x != nil {
		return x.NetworkIndex
	}
	return 0
}

func (x *AddNetworkRequest) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *AddNetworkRequest) GetListenPort() uint32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *AddNetworkRequest) GetPeerEndpoint() string {
	if x != nil {
		return x.PeerEndpoint
	}
	return ""
}

func (x *AddNetworkRequest) GetPeerPublicKey() string {
	if x != nil {
		return x.PeerPublicKey
	}
	return ""
}

func (x *AddNetworkRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AddNetworkRequest) GetNetworkCidr() string {
	if x != nil {
		return x.NetworkCidr
	}
	return ""
}

func (x *AddNetworkRequest) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *AddNetworkRequest) GetHostIp() string {
	if x != nil {
		return x.HostIp
	}
	return ""
}

type AddNetworkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Number of networks now configured
	TotalNetworks uint32 `protobuf:"varint,3,opt,name=total_networks,json=totalNetworks,proto3" json:"total_networks,omitempty"`
	// WireGuard interface name created (wg0, wg1, wg2, etc.)
	WgInterface string `protobuf:"bytes,4,opt,name=wg_interface,json=wgInterface,proto3" json:"wg_interface,omitempty"`
	// Container interface name (eth0, eth1, eth2, etc.)
	EthInterface string `protobuf:"bytes,5,opt,name=eth_interface,json=ethInterface,proto3" json:"eth_interface,omitempty"`
	// Public key for this interface (for peer configuration)
	PublicKey     string `protobuf:"bytes,6,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNetworkResponse) Reset() {
	*x = AddNetworkResponse{}
	mi := &file_wireguard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNetworkResponse) ProtoMessage() {}

func (x *AddNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wireguard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNetworkResponse.ProtoReflect.Descriptor instead.
func (*AddNetworkResponse) Descriptor() ([]byte, []int) {
	return file_wireguard_proto_rawDescGZIP(), []int{1}
}

func (x *AddNetworkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddNetworkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AddNetworkResponse) GetTotalNetworks() uint32 {
	if x != nil {
		return x.TotalNetworks
	}
	return 0
}

func (x *AddNetworkResponse) GetWgInterface() string {
	if x != nil {
		return x.WgInterface
	}
	return ""
}

func (x *AddNetworkResponse) GetEthInterface() string {
	if x != nil {
		return x.EthInterface
	}
	return ""
}

func (x *AddNetworkResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

// Request to remove a network from the container
type RemoveNetworkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Network ID to remove
	NetworkId string `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	// Network index (0, 1, 2, etc.) - identifies which wgN/ethN to remove
	NetworkIndex  uint32 `protobuf:"varint,2,opt,name=network_index,json=networkIndex,proto3" json:"network_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNetworkRequest) Reset() {
	*x = RemoveNetworkRequest{}
	mi := &file_wireguard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNetworkRequest) ProtoMessage() {}

func (x *RemoveNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wireguard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNetworkRequest.ProtoReflect.Descriptor instead.
func (*RemoveNetworkRequest) Descriptor() ([]byte, []int) {
	return file_wireguard_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveNetworkRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *RemoveNetworkRequest) GetNetworkIndex() uint32 {
	if x != nil {
		return x.NetworkIndex
	}
	return 0
}

type RemoveNetworkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Number of networks still configured
	RemainingNetworks uint32 `protobuf:"varint,3,opt,name=remaining_networks,json=remainingNetworks,proto3" json:"remaining_networks,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RemoveNetworkResponse) Reset() {
	*x = RemoveNetworkResponse{}
	mi := &file_wireguard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNetworkResponse) ProtoMessage() {}

func (x *RemoveNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wireguard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNetworkResponse.ProtoReflect.Descriptor instead.
func (*RemoveNetworkResponse) Descriptor() ([]byte, []int) {
	return file_wireguard_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveNetworkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveNetworkResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RemoveNetworkResponse) GetRemainingNetworks() uint32 {
	if x != nil {
		return x.RemainingNetworks
	}
	return 0
}

// Request WireGuard status
type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_wireguard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wireguard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_wireguard_proto_rawDescGZIP(), []int{4}
}

type GetStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service version
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Number of networks configured
	NetworkCount uint32 `protobuf:"varint,2,opt,name=network_count,json=networkCount,proto3" json:"network_count,omitempty"`
	// WireGuard interface statuses (one per wgN interface)
	Interfaces []*InterfaceStatus `protobuf:"bytes,3,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	// Peer statistics (one per peer, grouped by interface)
	Peers         []*PeerStatus `protobuf:"bytes,4,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_wireguard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wireguard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_wireguard_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetStatusResponse) GetNetworkCount() uint32 {
	if x != nil {
		return x.NetworkCount
	}
	return 0
}

func (x *GetStatusResponse) GetInterfaces() []*InterfaceStatus {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *GetStatusResponse) GetPeers() []*PeerStatus {
	if x != nil {
		return x.Peers
	}
	return nil
}

type InterfaceStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Network ID this interface represents
	NetworkId string `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	// Interface name (wg0, wg1, wg2, etc.)
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Public key for this interface
	PublicKey string `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Listen port
	ListenPort uint32 `protobuf:"varint,4,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	// IP addresses assigned to interface
	IpAddresses   []string `protobuf:"bytes,5,rep,name=ip_addresses,json=ipAddresses,proto3" json:"ip_addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceStatus) Reset() {
	*x = InterfaceStatus{}
	mi := &file_wireguard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceStatus) ProtoMessage() {}

func (x *InterfaceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_wireguard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceStatus.ProtoReflect.Descriptor instead.
func (*InterfaceStatus) Descriptor() ([]byte, []int) {
	return file_wireguard_proto_rawDescGZIP(), []int{6}
}

func (x *InterfaceStatus) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *InterfaceStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InterfaceStatus) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *InterfaceStatus) GetListenPort() uint32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *InterfaceStatus) GetIpAddresses() []string {
	if x != nil {
		return x.IpAddresses
	}
	return nil
}

type PeerStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Network ID this peer represents
	NetworkId string `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	// Interface name this peer belongs to (wg0, wg1, wg2, etc.)
	InterfaceName string `protobuf:"bytes,2,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	// Peer public key
	PublicKey string `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Peer endpoint (IP:port)
	Endpoint string `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Allowed IPs for this peer
	AllowedIps []string `protobuf:"bytes,5,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	// Latest handshake timestamp (Unix seconds, 0 if never)
	LatestHandshake uint64 `protobuf:"varint,6,opt,name=latest_handshake,json=latestHandshake,proto3" json:"latest_handshake,omitempty"`
	// Transfer statistics
	Stats         *TransferStats `protobuf:"bytes,7,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerStatus) Reset() {
	*x = PeerStatus{}
	mi := &file_wireguard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerStatus) ProtoMessage() {}

func (x *PeerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_wireguard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerStatus.ProtoReflect.Descriptor instead.
func (*PeerStatus) Descriptor() ([]byte, []int) {
	return file_wireguard_proto_rawDescGZIP(), []int{7}
}

func (x *PeerStatus) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *PeerStatus) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *PeerStatus) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *PeerStatus) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *PeerStatus) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *PeerStatus) GetLatestHandshake() uint64 {
	if x != nil {
		return x.LatestHandshake
	}
	return 0
}

func (x *PeerStatus) GetStats() *TransferStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type TransferStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bytes received from this peer
	BytesReceived uint64 `protobuf:"varint,1,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	// Bytes sent to this peer
	BytesSent uint64 `protobuf:"varint,2,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	// Persistent keepalive interval (seconds, 0 if disabled)
	PersistentKeepalive uint32 `protobuf:"varint,3,opt,name=persistent_keepalive,json=persistentKeepalive,proto3" json:"persistent_keepalive,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TransferStats) Reset() {
	*x = TransferStats{}
	mi := &file_wireguard_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferStats) ProtoMessage() {}

func (x *TransferStats) ProtoReflect() protoreflect.Message {
	mi := &file_wireguard_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferStats.ProtoReflect.Descriptor instead.
func (*TransferStats) Descriptor() ([]byte, []int) {
	return file_wireguard_proto_rawDescGZIP(), []int{8}
}

func (x *TransferStats) GetBytesReceived() uint64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *TransferStats) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *TransferStats) GetPersistentKeepalive() uint32 {
	if x != nil {
		return x.PersistentKeepalive
	}
	return 0
}

// Request for vmnet endpoint information
type GetVmnetEndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVmnetEndpointRequest) Reset() {
	*x = GetVmnetEndpointRequest{}
	mi := &file_wireguard_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVmnetEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVmnetEndpointRequest) ProtoMessage() {}

func (x *GetVmnetEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wireguard_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVmnetEndpointRequest.ProtoReflect.Descriptor instead.
func (*GetVmnetEndpointRequest) Descriptor() ([]byte, []int) {
	return file_wireguard_proto_rawDescGZIP(), []int{9}
}

type GetVmnetEndpointResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// vmnet endpoint (eth0 IP:port, e.g., "192.168.65.5:51820")
	Endpoint      string `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVmnetEndpointResponse) Reset() {
	*x = GetVmnetEndpointResponse{}
	mi := &file_wireguard_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVmnetEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVmnetEndpointResponse) ProtoMessage() {}

func (x *GetVmnetEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wireguard_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVmnetEndpointResponse.ProtoReflect.Descriptor instead.
func (*GetVmnetEndpointResponse) Descriptor() ([]byte, []int) {
	return file_wireguard_proto_rawDescGZIP(), []int{10}
}

func (x *GetVmnetEndpointResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetVmnetEndpointResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetVmnetEndpointResponse) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

// Request to add a peer to a WireGuard interface
type AddPeerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Network ID this peer belongs to
	NetworkId string `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	// Network index (which wgN interface to add peer to)
	NetworkIndex uint32 `protobuf:"varint,2,opt,name=network_index,json=networkIndex,proto3" json:"network_index,omitempty"`
	// Peer's WireGuard public key (Base64-encoded)
	PeerPublicKey string `protobuf:"bytes,3,opt,name=peer_public_key,json=peerPublicKey,proto3" json:"peer_public_key,omitempty"`
	// Peer's vmnet endpoint (IP:port, e.g., "192.168.65.5:51820")
	PeerEndpoint string `protobuf:"bytes,4,opt,name=peer_endpoint,json=peerEndpoint,proto3" json:"peer_endpoint,omitempty"`
	// Peer's overlay IP address (for allowed-ips routing, e.g., "172.18.0.3")
	PeerIpAddress string `protobuf:"bytes,5,opt,name=peer_ip_address,json=peerIpAddress,proto3" json:"peer_ip_address,omitempty"`
	// Peer's container name (for DNS resolution, e.g., "web1")
	PeerName string `protobuf:"bytes,6,opt,name=peer_name,json=peerName,proto3" json:"peer_name,omitempty"`
	// Peer's container ID (Docker ID, for logging/debugging)
	PeerContainerId string `protobuf:"bytes,7,opt,name=peer_container_id,json=peerContainerId,proto3" json:"peer_container_id,omitempty"`
	// Peer's DNS aliases (additional names that resolve to this IP)
	PeerAliases   []string `protobuf:"bytes,8,rep,name=peer_aliases,json=peerAliases,proto3" json:"peer_aliases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPeerRequest) Reset() {
	*x = AddPeerRequest{}
	mi := &file_wireguard_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPeerRequest) ProtoMessage() {}

func (x *AddPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wireguard_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPeerRequest.ProtoReflect.Descriptor instead.
func (*AddPeerRequest) Descriptor() ([]byte, []int) {
	return file_wireguard_proto_rawDescGZIP(), []int{11}
}

func (x *AddPeerRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *AddPeerRequest) GetNetworkIndex() uint32 {
	if x != nil {
		return x.NetworkIndex
	}
	return 0
}

func (x *AddPeerRequest) GetPeerPublicKey() string {
	if x != nil {
		return x.PeerPublicKey
	}
	return ""
}

func (x *AddPeerRequest) GetPeerEndpoint() string {
	if x != nil {
		return x.PeerEndpoint
	}
	return ""
}

func (x *AddPeerRequest) GetPeerIpAddress() string {
	if x != nil {
		return x.PeerIpAddress
	}
	return ""
}

func (x *AddPeerRequest) GetPeerName() string {
	if x != nil {
		return x.PeerName
	}
	return ""
}

func (x *AddPeerRequest) GetPeerContainerId() string {
	if x != nil {
		return x.PeerContainerId
	}
	return ""
}

func (x *AddPeerRequest) GetPeerAliases() []string {
	if x != nil {
		return x.PeerAliases
	}
	return nil
}

type AddPeerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Total number of peers on this interface
	TotalPeers    uint32 `protobuf:"varint,3,opt,name=total_peers,json=totalPeers,proto3" json:"total_peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPeerResponse) Reset() {
	*x = AddPeerResponse{}
	mi := &file_wireguard_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPeerResponse) ProtoMessage() {}

func (x *AddPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wireguard_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPeerResponse.ProtoReflect.Descriptor instead.
func (*AddPeerResponse) Descriptor() ([]byte, []int) {
	return file_wireguard_proto_rawDescGZIP(), []int{12}
}

func (x *AddPeerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddPeerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AddPeerResponse) GetTotalPeers() uint32 {
	if x != nil {
		return x.TotalPeers
	}
	return 0
}

// Request to remove a peer from a WireGuard interface
type RemovePeerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Network ID this peer belongs to
	NetworkId string `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	// Network index (which wgN interface to remove peer from)
	NetworkIndex uint32 `protobuf:"varint,2,opt,name=network_index,json=networkIndex,proto3" json:"network_index,omitempty"`
	// Peer's WireGuard public key to remove (Base64-encoded)
	PeerPublicKey string `protobuf:"bytes,3,opt,name=peer_public_key,json=peerPublicKey,proto3" json:"peer_public_key,omitempty"`
	// Peer's container name (for DNS entry removal)
	PeerName      string `protobuf:"bytes,4,opt,name=peer_name,json=peerName,proto3" json:"peer_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePeerRequest) Reset() {
	*x = RemovePeerRequest{}
	mi := &file_wireguard_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePeerRequest) ProtoMessage() {}

func (x *RemovePeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wireguard_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePeerRequest.ProtoReflect.Descriptor instead.
func (*RemovePeerRequest) Descriptor() ([]byte, []int) {
	return file_wireguard_proto_rawDescGZIP(), []int{13}
}

func (x *RemovePeerRequest) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *RemovePeerRequest) GetNetworkIndex() uint32 {
	if x != nil {
		return x.NetworkIndex
	}
	return 0
}

func (x *RemovePeerRequest) GetPeerPublicKey() string {
	if x != nil {
		return x.PeerPublicKey
	}
	return ""
}

func (x *RemovePeerRequest) GetPeerName() string {
	if x != nil {
		return x.PeerName
	}
	return ""
}

type RemovePeerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Remaining number of peers on this interface
	RemainingPeers uint32 `protobuf:"varint,3,opt,name=remaining_peers,json=remainingPeers,proto3" json:"remaining_peers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RemovePeerResponse) Reset() {
	*x = RemovePeerResponse{}
	mi := &file_wireguard_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePeerResponse) ProtoMessage() {}

func (x *RemovePeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wireguard_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePeerResponse.ProtoReflect.Descriptor instead.
func (*RemovePeerResponse) Descriptor() ([]byte, []int) {
	return file_wireguard_proto_rawDescGZIP(), []int{14}
}

func (x *RemovePeerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemovePeerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RemovePeerResponse) GetRemainingPeers() uint32 {
	if x != nil {
		return x.RemainingPeers
	}
	return 0
}

// Request to publish a port (expose container port on host)
type PublishPortRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protocol ("tcp" or "udp")
	Protocol string `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// Host port (port on vmnet interface that macOS host will connect to)
	HostPort uint32 `protobuf:"varint,2,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	// Container overlay IP address (WireGuard IP, e.g., "172.18.0.2")
	ContainerIp string `protobuf:"bytes,3,opt,name=container_ip,json=containerIp,proto3" json:"container_ip,omitempty"`
	// Container port (port inside container to DNAT to)
	ContainerPort uint32 `protobuf:"varint,4,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishPortRequest) Reset() {
	*x = PublishPortRequest{}
	mi := &file_wireguard_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishPortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishPortRequest) ProtoMessage() {}

func (x *PublishPortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wireguard_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishPortRequest.ProtoReflect.Descriptor instead.
func (*PublishPortRequest) Descriptor() ([]byte, []int) {
	return file_wireguard_proto_rawDescGZIP(), []int{15}
}

func (x *PublishPortRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *PublishPortRequest) GetHostPort() uint32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

func (x *PublishPortRequest) GetContainerIp() string {
	if x != nil {
		return x.ContainerIp
	}
	return ""
}

func (x *PublishPortRequest) GetContainerPort() uint32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

type PublishPortResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishPortResponse) Reset() {
	*x = PublishPortResponse{}
	mi := &file_wireguard_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishPortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishPortResponse) ProtoMessage() {}

func (x *PublishPortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wireguard_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishPortResponse.ProtoReflect.Descriptor instead.
func (*PublishPortResponse) Descriptor() ([]byte, []int) {
	return file_wireguard_proto_rawDescGZIP(), []int{16}
}

func (x *PublishPortResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PublishPortResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Request to unpublish a port (remove port exposure)
type UnpublishPortRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protocol ("tcp" or "udp")
	Protocol string `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// Host port to unpublish
	HostPort      uint32 `protobuf:"varint,2,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnpublishPortRequest) Reset() {
	*x = UnpublishPortRequest{}
	mi := &file_wireguard_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnpublishPortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpublishPortRequest) ProtoMessage() {}

func (x *UnpublishPortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wireguard_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpublishPortRequest.ProtoReflect.Descriptor instead.
func (*UnpublishPortRequest) Descriptor() ([]byte, []int) {
	return file_wireguard_proto_rawDescGZIP(), []int{17}
}

func (x *UnpublishPortRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *UnpublishPortRequest) GetHostPort() uint32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

type UnpublishPortResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnpublishPortResponse) Reset() {
	*x = UnpublishPortResponse{}
	mi := &file_wireguard_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnpublishPortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpublishPortResponse) ProtoMessage() {}

func (x *UnpublishPortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wireguard_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpublishPortResponse.ProtoReflect.Descriptor instead.
func (*UnpublishPortResponse) Descriptor() ([]byte, []int) {
	return file_wireguard_proto_rawDescGZIP(), []int{18}
}

func (x *UnpublishPortResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnpublishPortResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Request to dump nftables state for debugging
type DumpNftablesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DumpNftablesRequest) Reset() {
	*x = DumpNftablesRequest{}
	mi := &file_wireguard_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DumpNftablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DumpNftablesRequest) ProtoMessage() {}

func (x *DumpNftablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wireguard_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DumpNftablesRequest.ProtoReflect.Descriptor instead.
func (*DumpNftablesRequest) Descriptor() ([]byte, []int) {
	return file_wireguard_proto_rawDescGZIP(), []int{19}
}

type DumpNftablesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Full nftables ruleset output (from 'nft list ruleset')
	// Includes all tables, chains, rules, and packet counters
	Ruleset       string `protobuf:"bytes,3,opt,name=ruleset,proto3" json:"ruleset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DumpNftablesResponse) Reset() {
	*x = DumpNftablesResponse{}
	mi := &file_wireguard_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DumpNftablesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DumpNftablesResponse) ProtoMessage() {}

func (x *DumpNftablesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wireguard_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DumpNftablesResponse.ProtoReflect.Descriptor instead.
func (*DumpNftablesResponse) Descriptor() ([]byte, []int) {
	return file_wireguard_proto_rawDescGZIP(), []int{20}
}

func (x *DumpNftablesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DumpNftablesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DumpNftablesResponse) GetRuleset() string {
	if x != nil {
		return x.Ruleset
	}
	return ""
}

var File_wireguard_proto protoreflect.FileDescriptor

const file_wireguard_proto_rawDesc = "" +
	"\n" +
	"\x0fwireguard.proto\x12\x11arca.wireguard.v1\"\xdb\x02\n" +
	"\x11AddNetworkRequest\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12#\n" +
	"\rnetwork_index\x18\x02 \x01(\rR\fnetworkIndex\x12\x1f\n" +
	"\vprivate_key\x18\x03 \x01(\tR\n" +
	"privateKey\x12\x1f\n" +
	"\vlisten_port\x18\x04 \x01(\rR\n" +
	"listenPort\x12#\n" +
	"\rpeer_endpoint\x18\x05 \x01(\tR\fpeerEndpoint\x12&\n" +
	"\x0fpeer_public_key\x18\x06 \x01(\tR\rpeerPublicKey\x12\x1d\n" +
	"\n" +
	"ip_address\x18\a \x01(\tR\tipAddress\x12!\n" +
	"\fnetwork_cidr\x18\b \x01(\tR\vnetworkCidr\x12\x18\n" +
	"\agateway\x18\t \x01(\tR\agateway\x12\x17\n" +
	"\ahost_ip\x18\n" +
	" \x01(\tR\x06hostIp\"\xd2\x01\n" +
	"\x12AddNetworkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12%\n" +
	"\x0etotal_networks\x18\x03 \x01(\rR\rtotalNetworks\x12!\n" +
	"\fwg_interface\x18\x04 \x01(\tR\vwgInterface\x12#\n" +
	"\reth_interface\x18\x05 \x01(\tR\fethInterface\x12\x1d\n" +
	"\n" +
	"public_key\x18\x06 \x01(\tR\tpublicKey\"Z\n" +
	"\x14RemoveNetworkRequest\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12#\n" +
	"\rnetwork_index\x18\x02 \x01(\rR\fnetworkIndex\"v\n" +
	"\x15RemoveNetworkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12-\n" +
	"\x12remaining_networks\x18\x03 \x01(\rR\x11remainingNetworks\"\x12\n" +
	"\x10GetStatusRequest\"\xcb\x01\n" +
	"\x11GetStatusResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12#\n" +
	"\rnetwork_count\x18\x02 \x01(\rR\fnetworkCount\x12B\n" +
	"\n" +
	"interfaces\x18\x03 \x03(\v2\".arca.wireguard.v1.InterfaceStatusR\n" +
	"interfaces\x123\n" +
	"\x05peers\x18\x04 \x03(\v2\x1d.arca.wireguard.v1.PeerStatusR\x05peers\"\xa7\x01\n" +
	"\x0fInterfaceStatus\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\x1f\n" +
	"\vlisten_port\x18\x04 \x01(\rR\n" +
	"listenPort\x12!\n" +
	"\fip_addresses\x18\x05 \x03(\tR\vipAddresses\"\x91\x02\n" +
	"\n" +
	"PeerStatus\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12%\n" +
	"\x0einterface_name\x18\x02 \x01(\tR\rinterfaceName\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\x12\x1f\n" +
	"\vallowed_ips\x18\x05 \x03(\tR\n" +
	"allowedIps\x12)\n" +
	"\x10latest_handshake\x18\x06 \x01(\x04R\x0flatestHandshake\x126\n" +
	"\x05stats\x18\a \x01(\v2 .arca.wireguard.v1.TransferStatsR\x05stats\"\x88\x01\n" +
	"\rTransferStats\x12%\n" +
	"\x0ebytes_received\x18\x01 \x01(\x04R\rbytesReceived\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x02 \x01(\x04R\tbytesSent\x121\n" +
	"\x14persistent_keepalive\x18\x03 \x01(\rR\x13persistentKeepalive\"\x19\n" +
	"\x17GetVmnetEndpointRequest\"f\n" +
	"\x18GetVmnetEndpointResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\"\xb5\x02\n" +
	"\x0eAddPeerRequest\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12#\n" +
	"\rnetwork_index\x18\x02 \x01(\rR\fnetworkIndex\x12&\n" +
	"\x0fpeer_public_key\x18\x03 \x01(\tR\rpeerPublicKey\x12#\n" +
	"\rpeer_endpoint\x18\x04 \x01(\tR\fpeerEndpoint\x12&\n" +
	"\x0fpeer_ip_address\x18\x05 \x01(\tR\rpeerIpAddress\x12\x1b\n" +
	"\tpeer_name\x18\x06 \x01(\tR\bpeerName\x12*\n" +
	"\x11peer_container_id\x18\a \x01(\tR\x0fpeerContainerId\x12!\n" +
	"\fpeer_aliases\x18\b \x03(\tR\vpeerAliases\"b\n" +
	"\x0fAddPeerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\vtotal_peers\x18\x03 \x01(\rR\n" +
	"totalPeers\"\x9c\x01\n" +
	"\x11RemovePeerRequest\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12#\n" +
	"\rnetwork_index\x18\x02 \x01(\rR\fnetworkIndex\x12&\n" +
	"\x0fpeer_public_key\x18\x03 \x01(\tR\rpeerPublicKey\x12\x1b\n" +
	"\tpeer_name\x18\x04 \x01(\tR\bpeerName\"m\n" +
	"\x12RemovePeerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12'\n" +
	"\x0fremaining_peers\x18\x03 \x01(\rR\x0eremainingPeers\"\x97\x01\n" +
	"\x12PublishPortRequest\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x1b\n" +
	"\thost_port\x18\x02 \x01(\rR\bhostPort\x12!\n" +
	"\fcontainer_ip\x18\x03 \x01(\tR\vcontainerIp\x12%\n" +
	"\x0econtainer_port\x18\x04 \x01(\rR\rcontainerPort\"E\n" +
	"\x13PublishPortResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"O\n" +
	"\x14UnpublishPortRequest\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x1b\n" +
	"\thost_port\x18\x02 \x01(\rR\bhostPort\"G\n" +
	"\x15UnpublishPortResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x15\n" +
	"\x13DumpNftablesRequest\"`\n" +
	"\x14DumpNftablesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\aruleset\x18\x03 \x01(\tR\aruleset2\xe6\x06\n" +
	"\x10WireGuardService\x12Y\n" +
	"\n" +
	"AddNetwork\x12$.arca.wireguard.v1.AddNetworkRequest\x1a%.arca.wireguard.v1.AddNetworkResponse\x12b\n" +
	"\rRemoveNetwork\x12'.arca.wireguard.v1.RemoveNetworkRequest\x1a(.arca.wireguard.v1.RemoveNetworkResponse\x12P\n" +
	"\aAddPeer\x12!.arca.wireguard.v1.AddPeerRequest\x1a\".arca.wireguard.v1.AddPeerResponse\x12Y\n" +
	"\n" +
	"RemovePeer\x12$.arca.wireguard.v1.RemovePeerRequest\x1a%.arca.wireguard.v1.RemovePeerResponse\x12V\n" +
	"\tGetStatus\x12#.arca.wireguard.v1.GetStatusRequest\x1a$.arca.wireguard.v1.GetStatusResponse\x12k\n" +
	"\x10GetVmnetEndpoint\x12*.arca.wireguard.v1.GetVmnetEndpointRequest\x1a+.arca.wireguard.v1.GetVmnetEndpointResponse\x12\\\n" +
	"\vPublishPort\x12%.arca.wireguard.v1.PublishPortRequest\x1a&.arca.wireguard.v1.PublishPortResponse\x12b\n" +
	"\rUnpublishPort\x12'.arca.wireguard.v1.UnpublishPortRequest\x1a(.arca.wireguard.v1.UnpublishPortResponse\x12_\n" +
	"\fDumpNftables\x12&.arca.wireguard.v1.DumpNftablesRequest\x1a'.arca.wireguard.v1.DumpNftablesResponseB5Z3github.com/vas-solutus/arca-wireguard-service/protob\x06proto3"

var (
	file_wireguard_proto_rawDescOnce sync.Once
	file_wireguard_proto_rawDescData []byte
)

func file_wireguard_proto_rawDescGZIP() []byte {
	file_wireguard_proto_rawDescOnce.Do(func() {
		file_wireguard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wireguard_proto_rawDesc), len(file_wireguard_proto_rawDesc)))
	})
	return file_wireguard_proto_rawDescData
}

var file_wireguard_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_wireguard_proto_goTypes = []any{
	(*AddNetworkRequest)(nil),        // 0: arca.wireguard.v1.AddNetworkRequest
	(*AddNetworkResponse)(nil),       // 1: arca.wireguard.v1.AddNetworkResponse
	(*RemoveNetworkRequest)(nil),     // 2: arca.wireguard.v1.RemoveNetworkRequest
	(*RemoveNetworkResponse)(nil),    // 3: arca.wireguard.v1.RemoveNetworkResponse
	(*GetStatusRequest)(nil),         // 4: arca.wireguard.v1.GetStatusRequest
	(*GetStatusResponse)(nil),        // 5: arca.wireguard.v1.GetStatusResponse
	(*InterfaceStatus)(nil),          // 6: arca.wireguard.v1.InterfaceStatus
	(*PeerStatus)(nil),               // 7: arca.wireguard.v1.PeerStatus
	(*TransferStats)(nil),            // 8: arca.wireguard.v1.TransferStats
	(*GetVmnetEndpointRequest)(nil),  // 9: arca.wireguard.v1.GetVmnetEndpointRequest
	(*GetVmnetEndpointResponse)(nil), // 10: arca.wireguard.v1.GetVmnetEndpointResponse
	(*AddPeerRequest)(nil),           // 11: arca.wireguard.v1.AddPeerRequest
	(*AddPeerResponse)(nil),          // 12: arca.wireguard.v1.AddPeerResponse
	(*RemovePeerRequest)(nil),        // 13: arca.wireguard.v1.RemovePeerRequest
	(*RemovePeerResponse)(nil),       // 14: arca.wireguard.v1.RemovePeerResponse
	(*PublishPortRequest)(nil),       // 15: arca.wireguard.v1.PublishPortRequest
	(*PublishPortResponse)(nil),      // 16: arca.wireguard.v1.PublishPortResponse
	(*UnpublishPortRequest)(nil),     // 17: arca.wireguard.v1.UnpublishPortRequest
	(*UnpublishPortResponse)(nil),    // 18: arca.wireguard.v1.UnpublishPortResponse
	(*DumpNftablesRequest)(nil),      // 19: arca.wireguard.v1.DumpNftablesRequest
	(*DumpNftablesResponse)(nil),     // 20: arca.wireguard.v1.DumpNftablesResponse
}
var file_wireguard_proto_depIdxs = []int32{
	6,  // 0: arca.wireguard.v1.GetStatusResponse.interfaces:type_name -> arca.wireguard.v1.InterfaceStatus
	7,  // 1: arca.wireguard.v1.GetStatusResponse.peers:type_name -> arca.wireguard.v1.PeerStatus
	8,  // 2: arca.wireguard.v1.PeerStatus.stats:type_name -> arca.wireguard.v1.TransferStats
	0,  // 3: arca.wireguard.v1.WireGuardService.AddNetwork:input_type -> arca.wireguard.v1.AddNetworkRequest
	2,  // 4: arca.wireguard.v1.WireGuardService.RemoveNetwork:input_type -> arca.wireguard.v1.RemoveNetworkRequest
	11, // 5: arca.wireguard.v1.WireGuardService.AddPeer:input_type -> arca.wireguard.v1.AddPeerRequest
	13, // 6: arca.wireguard.v1.WireGuardService.RemovePeer:input_type -> arca.wireguard.v1.RemovePeerRequest
	4,  // 7: arca.wireguard.v1.WireGuardService.GetStatus:input_type -> arca.wireguard.v1.GetStatusRequest
	9,  // 8: arca.wireguard.v1.WireGuardService.GetVmnetEndpoint:input_type -> arca.wireguard.v1.GetVmnetEndpointRequest
	15, // 9: arca.wireguard.v1.WireGuardService.PublishPort:input_type -> arca.wireguard.v1.PublishPortRequest
	17, // 10: arca.wireguard.v1.WireGuardService.UnpublishPort:input_type -> arca.wireguard.v1.UnpublishPortRequest
	19, // 11: arca.wireguard.v1.WireGuardService.DumpNftables:input_type -> arca.wireguard.v1.DumpNftablesRequest
	1,  // 12: arca.wireguard.v1.WireGuardService.AddNetwork:output_type -> arca.wireguard.v1.AddNetworkResponse
	3,  // 13: arca.wireguard.v1.WireGuardService.RemoveNetwork:output_type -> arca.wireguard.v1.RemoveNetworkResponse
	12, // 14: arca.wireguard.v1.WireGuardService.AddPeer:output_type -> arca.wireguard.v1.AddPeerResponse
	14, // 15: arca.wireguard.v1.WireGuardService.RemovePeer:output_type -> arca.wireguard.v1.RemovePeerResponse
	5,  // 16: arca.wireguard.v1.WireGuardService.GetStatus:output_type -> arca.wireguard.v1.GetStatusResponse
	10, // 17: arca.wireguard.v1.WireGuardService.GetVmnetEndpoint:output_type -> arca.wireguard.v1.GetVmnetEndpointResponse
	16, // 18: arca.wireguard.v1.WireGuardService.PublishPort:output_type -> arca.wireguard.v1.PublishPortResponse
	18, // 19: arca.wireguard.v1.WireGuardService.UnpublishPort:output_type -> arca.wireguard.v1.UnpublishPortResponse
	20, // 20: arca.wireguard.v1.WireGuardService.DumpNftables:output_type -> arca.wireguard.v1.DumpNftablesResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_wireguard_proto_init() }
func file_wireguard_proto_init() {
	if File_wireguard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wireguard_proto_rawDesc), len(file_wireguard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wireguard_proto_goTypes,
		DependencyIndexes: file_wireguard_proto_depIdxs,
		MessageInfos:      file_wireguard_proto_msgTypes,
	}.Build()
	File_wireguard_proto = out.File
	file_wireguard_proto_goTypes = nil
	file_wireguard_proto_depIdxs = nil
}
