// Arca Container Filesystem Service Protocol
// gRPC API for container filesystem operations
//
// This service runs on vsock port 51821 in each container's Linux VM
// and provides filesystem operations including:
// - Filesystem sync (flush buffers)
// - Archive operations (tar creation/extraction for buildx)
// - OverlayFS upperdir enumeration (for docker diff)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: filesystem.proto

package filesystem

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to check service readiness
type ReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyRequest) Reset() {
	*x = ReadyRequest{}
	mi := &file_filesystem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyRequest) ProtoMessage() {}

func (x *ReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyRequest.ProtoReflect.Descriptor instead.
func (*ReadyRequest) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{0}
}

// Response indicating service readiness
type ReadyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if service is fully initialized and ready
	Ready bool `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	// Service version
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Milliseconds since service started
	UptimeMs      int64 `protobuf:"varint,3,opt,name=uptime_ms,json=uptimeMs,proto3" json:"uptime_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyResponse) Reset() {
	*x = ReadyResponse{}
	mi := &file_filesystem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyResponse) ProtoMessage() {}

func (x *ReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyResponse.ProtoReflect.Descriptor instead.
func (*ReadyResponse) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{1}
}

func (x *ReadyResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *ReadyResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ReadyResponse) GetUptimeMs() int64 {
	if x != nil {
		return x.UptimeMs
	}
	return 0
}

// Request to sync filesystem (flush all cached writes)
type SyncFilesystemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncFilesystemRequest) Reset() {
	*x = SyncFilesystemRequest{}
	mi := &file_filesystem_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFilesystemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFilesystemRequest) ProtoMessage() {}

func (x *SyncFilesystemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFilesystemRequest.ProtoReflect.Descriptor instead.
func (*SyncFilesystemRequest) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{2}
}

type SyncFilesystemResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncFilesystemResponse) Reset() {
	*x = SyncFilesystemResponse{}
	mi := &file_filesystem_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFilesystemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFilesystemResponse) ProtoMessage() {}

func (x *SyncFilesystemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFilesystemResponse.ProtoReflect.Descriptor instead.
func (*SyncFilesystemResponse) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{3}
}

func (x *SyncFilesystemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncFilesystemResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Request to enumerate OverlayFS upperdir for container diff
type EnumerateUpperdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumerateUpperdirRequest) Reset() {
	*x = EnumerateUpperdirRequest{}
	mi := &file_filesystem_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumerateUpperdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumerateUpperdirRequest) ProtoMessage() {}

func (x *EnumerateUpperdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumerateUpperdirRequest.ProtoReflect.Descriptor instead.
func (*EnumerateUpperdirRequest) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{4}
}

type EnumerateUpperdirResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Files and directories in upperdir
	Entries       []*UpperdirEntry `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumerateUpperdirResponse) Reset() {
	*x = EnumerateUpperdirResponse{}
	mi := &file_filesystem_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumerateUpperdirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumerateUpperdirResponse) ProtoMessage() {}

func (x *EnumerateUpperdirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumerateUpperdirResponse.ProtoReflect.Descriptor instead.
func (*EnumerateUpperdirResponse) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{5}
}

func (x *EnumerateUpperdirResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EnumerateUpperdirResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *EnumerateUpperdirResponse) GetEntries() []*UpperdirEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Represents a file, directory, or whiteout in the OverlayFS upperdir
type UpperdirEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path relative to container root (e.g., "/etc/hosts", "/tmp/myfile")
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Entry type: "file", "dir", "symlink", "whiteout"
	// "whiteout" indicates a deleted file (character device 0/0 in upperdir)
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// File size in bytes (0 for directories and whiteouts)
	Size int64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// Modification time (Unix timestamp seconds)
	Mtime int64 `protobuf:"varint,4,opt,name=mtime,proto3" json:"mtime,omitempty"`
	// File mode/permissions (Unix mode bits)
	Mode          uint32 `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpperdirEntry) Reset() {
	*x = UpperdirEntry{}
	mi := &file_filesystem_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpperdirEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpperdirEntry) ProtoMessage() {}

func (x *UpperdirEntry) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpperdirEntry.ProtoReflect.Descriptor instead.
func (*UpperdirEntry) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{6}
}

func (x *UpperdirEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UpperdirEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpperdirEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UpperdirEntry) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *UpperdirEntry) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

// Request to read archive from filesystem path
type ReadArchiveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container ID (for resolving /run/container/{id}/rootfs path)
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// Path to file or directory to archive (e.g., "/tmp/myfile.txt" or "/etc")
	Path          string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadArchiveRequest) Reset() {
	*x = ReadArchiveRequest{}
	mi := &file_filesystem_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadArchiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadArchiveRequest) ProtoMessage() {}

func (x *ReadArchiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadArchiveRequest.ProtoReflect.Descriptor instead.
func (*ReadArchiveRequest) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{7}
}

func (x *ReadArchiveRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ReadArchiveRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadArchiveResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Tar archive data (gzip compressed)
	TarData []byte `protobuf:"bytes,3,opt,name=tar_data,json=tarData,proto3" json:"tar_data,omitempty"`
	// File stat information (for X-Docker-Container-Path-Stat header)
	Stat          *PathStat `protobuf:"bytes,4,opt,name=stat,proto3" json:"stat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadArchiveResponse) Reset() {
	*x = ReadArchiveResponse{}
	mi := &file_filesystem_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadArchiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadArchiveResponse) ProtoMessage() {}

func (x *ReadArchiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadArchiveResponse.ProtoReflect.Descriptor instead.
func (*ReadArchiveResponse) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{8}
}

func (x *ReadArchiveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReadArchiveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReadArchiveResponse) GetTarData() []byte {
	if x != nil {
		return x.TarData
	}
	return nil
}

func (x *ReadArchiveResponse) GetStat() *PathStat {
	if x != nil {
		return x.Stat
	}
	return nil
}

// File stat information for archived paths
type PathStat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// File or directory name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// File size in bytes
	Size int64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// File mode/permissions (os.FileMode as uint32)
	Mode uint32 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	// Modification time (RFC3339 format: "2006-01-02T15:04:05Z07:00")
	Mtime string `protobuf:"bytes,4,opt,name=mtime,proto3" json:"mtime,omitempty"`
	// Symbolic link target (empty if not a symlink)
	LinkTarget    string `protobuf:"bytes,5,opt,name=link_target,json=linkTarget,proto3" json:"link_target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathStat) Reset() {
	*x = PathStat{}
	mi := &file_filesystem_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathStat) ProtoMessage() {}

func (x *PathStat) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathStat.ProtoReflect.Descriptor instead.
func (*PathStat) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{9}
}

func (x *PathStat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PathStat) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PathStat) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *PathStat) GetMtime() string {
	if x != nil {
		return x.Mtime
	}
	return ""
}

func (x *PathStat) GetLinkTarget() string {
	if x != nil {
		return x.LinkTarget
	}
	return ""
}

// Request to write archive to filesystem path
type WriteArchiveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container ID (for resolving /run/container/{id}/rootfs path)
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// Destination path where archive should be extracted (e.g., "/tmp")
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Tar archive data to extract
	TarData       []byte `protobuf:"bytes,3,opt,name=tar_data,json=tarData,proto3" json:"tar_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteArchiveRequest) Reset() {
	*x = WriteArchiveRequest{}
	mi := &file_filesystem_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteArchiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteArchiveRequest) ProtoMessage() {}

func (x *WriteArchiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteArchiveRequest.ProtoReflect.Descriptor instead.
func (*WriteArchiveRequest) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{10}
}

func (x *WriteArchiveRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *WriteArchiveRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteArchiveRequest) GetTarData() []byte {
	if x != nil {
		return x.TarData
	}
	return nil
}

type WriteArchiveResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteArchiveResponse) Reset() {
	*x = WriteArchiveResponse{}
	mi := &file_filesystem_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteArchiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteArchiveResponse) ProtoMessage() {}

func (x *WriteArchiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteArchiveResponse.ProtoReflect.Descriptor instead.
func (*WriteArchiveResponse) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{11}
}

func (x *WriteArchiveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WriteArchiveResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Request to create a bind mount inside the container
type CreateBindMountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container ID (for resolving /run/container/{id}/rootfs path)
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// Source path inside VM (absolute path, e.g., "/mnt/arca-file-mounts/abc123/myfile.txt")
	// Can be a file or directory
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// Target path relative to container root (e.g., "/test.txt" or "/app/config.yaml")
	// Will be resolved to /run/container/{container_id}/rootfs{target}
	Target string `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	// Read-only mount (default: false for read-write)
	ReadOnly      bool `protobuf:"varint,4,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBindMountRequest) Reset() {
	*x = CreateBindMountRequest{}
	mi := &file_filesystem_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBindMountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBindMountRequest) ProtoMessage() {}

func (x *CreateBindMountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBindMountRequest.ProtoReflect.Descriptor instead.
func (*CreateBindMountRequest) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{12}
}

func (x *CreateBindMountRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *CreateBindMountRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CreateBindMountRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *CreateBindMountRequest) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type CreateBindMountResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBindMountResponse) Reset() {
	*x = CreateBindMountResponse{}
	mi := &file_filesystem_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBindMountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBindMountResponse) ProtoMessage() {}

func (x *CreateBindMountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBindMountResponse.ProtoReflect.Descriptor instead.
func (*CreateBindMountResponse) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{13}
}

func (x *CreateBindMountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateBindMountResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Request to stat a path (check existence and get metadata)
type StatPathRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container ID (for resolving /run/container/{id}/rootfs path)
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// Path to stat (e.g., "/tmp/myfile.txt")
	Path          string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatPathRequest) Reset() {
	*x = StatPathRequest{}
	mi := &file_filesystem_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatPathRequest) ProtoMessage() {}

func (x *StatPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatPathRequest.ProtoReflect.Descriptor instead.
func (*StatPathRequest) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{14}
}

func (x *StatPathRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *StatPathRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StatPathResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// File stat information
	Stat          *PathStat `protobuf:"bytes,3,opt,name=stat,proto3" json:"stat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatPathResponse) Reset() {
	*x = StatPathResponse{}
	mi := &file_filesystem_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatPathResponse) ProtoMessage() {}

func (x *StatPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatPathResponse.ProtoReflect.Descriptor instead.
func (*StatPathResponse) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{15}
}

func (x *StatPathResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StatPathResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StatPathResponse) GetStat() *PathStat {
	if x != nil {
		return x.Stat
	}
	return nil
}

// Request to create an OverlayFS mount for a volume
// This overlays an EXT4 writable layer on top of a VirtioFS layer
// Provides full POSIX compliance (Unix sockets, chmod) for volumes
type CreateVolumeOverlayRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container ID (for resolving container rootfs path)
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// Lower layer path - where VirtioFS should be mounted in guest
	// e.g., "/mnt/arca-volumes/{hash}/data"
	// Go will mount the VirtioFS here if not already mounted
	LowerPath string `protobuf:"bytes,2,opt,name=lower_path,json=lowerPath,proto3" json:"lower_path,omitempty"`
	// Upper layer identifier - volume name for creating subdirs
	// Used to create /mnt/vdb/volume-overlays/{upper_device}/upper and work
	UpperDevice string `protobuf:"bytes,3,opt,name=upper_device,json=upperDevice,proto3" json:"upper_device,omitempty"`
	// Target mount path relative to container root
	// e.g., "/var/lib/rancher/k3s"
	// Will be resolved to /run/container/{container_id}/rootfs{target}
	Target string `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	// VirtioFS tag for mounting the share if not already mounted
	// This is the hash of the host source path used by the hypervisor
	VirtiofsTag   string `protobuf:"bytes,5,opt,name=virtiofs_tag,json=virtiofsTag,proto3" json:"virtiofs_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVolumeOverlayRequest) Reset() {
	*x = CreateVolumeOverlayRequest{}
	mi := &file_filesystem_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVolumeOverlayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVolumeOverlayRequest) ProtoMessage() {}

func (x *CreateVolumeOverlayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVolumeOverlayRequest.ProtoReflect.Descriptor instead.
func (*CreateVolumeOverlayRequest) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{16}
}

func (x *CreateVolumeOverlayRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *CreateVolumeOverlayRequest) GetLowerPath() string {
	if x != nil {
		return x.LowerPath
	}
	return ""
}

func (x *CreateVolumeOverlayRequest) GetUpperDevice() string {
	if x != nil {
		return x.UpperDevice
	}
	return ""
}

func (x *CreateVolumeOverlayRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *CreateVolumeOverlayRequest) GetVirtiofsTag() string {
	if x != nil {
		return x.VirtiofsTag
	}
	return ""
}

type CreateVolumeOverlayResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVolumeOverlayResponse) Reset() {
	*x = CreateVolumeOverlayResponse{}
	mi := &file_filesystem_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVolumeOverlayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVolumeOverlayResponse) ProtoMessage() {}

func (x *CreateVolumeOverlayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVolumeOverlayResponse.ProtoReflect.Descriptor instead.
func (*CreateVolumeOverlayResponse) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{17}
}

func (x *CreateVolumeOverlayResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateVolumeOverlayResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Request to create a direct EXT4 bind mount for a volume
// This creates a directory on the writable EXT4 filesystem and bind mounts it
// to the container target path. No OverlayFS involved - allows nested overlays.
type CreateDirectMountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container ID (for resolving container rootfs path)
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// Volume name - used to create /mnt/writable/volumes/{volume_name}
	VolumeName string `protobuf:"bytes,2,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"`
	// Target mount path relative to container root
	// e.g., "/var/lib/rancher/k3s"
	// Will be resolved to /run/container/{container_id}/rootfs{target}
	Target        string `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectMountRequest) Reset() {
	*x = CreateDirectMountRequest{}
	mi := &file_filesystem_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectMountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectMountRequest) ProtoMessage() {}

func (x *CreateDirectMountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectMountRequest.ProtoReflect.Descriptor instead.
func (*CreateDirectMountRequest) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{18}
}

func (x *CreateDirectMountRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *CreateDirectMountRequest) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

func (x *CreateDirectMountRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type CreateDirectMountResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectMountResponse) Reset() {
	*x = CreateDirectMountResponse{}
	mi := &file_filesystem_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectMountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectMountResponse) ProtoMessage() {}

func (x *CreateDirectMountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectMountResponse.ProtoReflect.Descriptor instead.
func (*CreateDirectMountResponse) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{19}
}

func (x *CreateDirectMountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateDirectMountResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Request to generate /etc/hosts file for a container
// Docker generates this file with localhost entries and container hostname
type GenerateHostsFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container ID (for resolving container rootfs path)
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// Container hostname (typically the short container ID or user-specified hostname)
	Hostname string `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Container's IP address (e.g., "10.89.0.2")
	IpAddress string `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// Container name (without leading slash, e.g., "my-container")
	ContainerName string `protobuf:"bytes,4,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	// Extra hosts to add (from --add-host flag)
	// Format: "hostname:ip"
	ExtraHosts    []string `protobuf:"bytes,5,rep,name=extra_hosts,json=extraHosts,proto3" json:"extra_hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateHostsFileRequest) Reset() {
	*x = GenerateHostsFileRequest{}
	mi := &file_filesystem_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateHostsFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateHostsFileRequest) ProtoMessage() {}

func (x *GenerateHostsFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateHostsFileRequest.ProtoReflect.Descriptor instead.
func (*GenerateHostsFileRequest) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{20}
}

func (x *GenerateHostsFileRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *GenerateHostsFileRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *GenerateHostsFileRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *GenerateHostsFileRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *GenerateHostsFileRequest) GetExtraHosts() []string {
	if x != nil {
		return x.ExtraHosts
	}
	return nil
}

type GenerateHostsFileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success status
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if success = false
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateHostsFileResponse) Reset() {
	*x = GenerateHostsFileResponse{}
	mi := &file_filesystem_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateHostsFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateHostsFileResponse) ProtoMessage() {}

func (x *GenerateHostsFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filesystem_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateHostsFileResponse.ProtoReflect.Descriptor instead.
func (*GenerateHostsFileResponse) Descriptor() ([]byte, []int) {
	return file_filesystem_proto_rawDescGZIP(), []int{21}
}

func (x *GenerateHostsFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GenerateHostsFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_filesystem_proto protoreflect.FileDescriptor

const file_filesystem_proto_rawDesc = "" +
	"\n" +
	"\x10filesystem.proto\x12\x12arca.filesystem.v1\"\x0e\n" +
	"\fReadyRequest\"\\\n" +
	"\rReadyResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1b\n" +
	"\tuptime_ms\x18\x03 \x01(\x03R\buptimeMs\"\x17\n" +
	"\x15SyncFilesystemRequest\"H\n" +
	"\x16SyncFilesystemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x1a\n" +
	"\x18EnumerateUpperdirRequest\"\x88\x01\n" +
	"\x19EnumerateUpperdirResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12;\n" +
	"\aentries\x18\x03 \x03(\v2!.arca.filesystem.v1.UpperdirEntryR\aentries\"u\n" +
	"\rUpperdirEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x14\n" +
	"\x05mtime\x18\x04 \x01(\x03R\x05mtime\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\rR\x04mode\"K\n" +
	"\x12ReadArchiveRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x92\x01\n" +
	"\x13ReadArchiveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x19\n" +
	"\btar_data\x18\x03 \x01(\fR\atarData\x120\n" +
	"\x04stat\x18\x04 \x01(\v2\x1c.arca.filesystem.v1.PathStatR\x04stat\"}\n" +
	"\bPathStat\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\x12\x14\n" +
	"\x05mtime\x18\x04 \x01(\tR\x05mtime\x12\x1f\n" +
	"\vlink_target\x18\x05 \x01(\tR\n" +
	"linkTarget\"g\n" +
	"\x13WriteArchiveRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x19\n" +
	"\btar_data\x18\x03 \x01(\fR\atarData\"F\n" +
	"\x14WriteArchiveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x88\x01\n" +
	"\x16CreateBindMountRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x1b\n" +
	"\tread_only\x18\x04 \x01(\bR\breadOnly\"I\n" +
	"\x17CreateBindMountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"H\n" +
	"\x0fStatPathRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"t\n" +
	"\x10StatPathResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x120\n" +
	"\x04stat\x18\x03 \x01(\v2\x1c.arca.filesystem.v1.PathStatR\x04stat\"\xbc\x01\n" +
	"\x1aCreateVolumeOverlayRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x1d\n" +
	"\n" +
	"lower_path\x18\x02 \x01(\tR\tlowerPath\x12!\n" +
	"\fupper_device\x18\x03 \x01(\tR\vupperDevice\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12!\n" +
	"\fvirtiofs_tag\x18\x05 \x01(\tR\vvirtiofsTag\"M\n" +
	"\x1bCreateVolumeOverlayResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"v\n" +
	"\x18CreateDirectMountRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x1f\n" +
	"\vvolume_name\x18\x02 \x01(\tR\n" +
	"volumeName\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\"K\n" +
	"\x19CreateDirectMountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xc0\x01\n" +
	"\x18GenerateHostsFileRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12%\n" +
	"\x0econtainer_name\x18\x04 \x01(\tR\rcontainerName\x12\x1f\n" +
	"\vextra_hosts\x18\x05 \x03(\tR\n" +
	"extraHosts\"K\n" +
	"\x19GenerateHostsFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\x9e\b\n" +
	"\x11FilesystemService\x12L\n" +
	"\x05Ready\x12 .arca.filesystem.v1.ReadyRequest\x1a!.arca.filesystem.v1.ReadyResponse\x12g\n" +
	"\x0eSyncFilesystem\x12).arca.filesystem.v1.SyncFilesystemRequest\x1a*.arca.filesystem.v1.SyncFilesystemResponse\x12p\n" +
	"\x11EnumerateUpperdir\x12,.arca.filesystem.v1.EnumerateUpperdirRequest\x1a-.arca.filesystem.v1.EnumerateUpperdirResponse\x12^\n" +
	"\vReadArchive\x12&.arca.filesystem.v1.ReadArchiveRequest\x1a'.arca.filesystem.v1.ReadArchiveResponse\x12a\n" +
	"\fWriteArchive\x12'.arca.filesystem.v1.WriteArchiveRequest\x1a(.arca.filesystem.v1.WriteArchiveResponse\x12j\n" +
	"\x0fCreateBindMount\x12*.arca.filesystem.v1.CreateBindMountRequest\x1a+.arca.filesystem.v1.CreateBindMountResponse\x12U\n" +
	"\bStatPath\x12#.arca.filesystem.v1.StatPathRequest\x1a$.arca.filesystem.v1.StatPathResponse\x12v\n" +
	"\x13CreateVolumeOverlay\x12..arca.filesystem.v1.CreateVolumeOverlayRequest\x1a/.arca.filesystem.v1.CreateVolumeOverlayResponse\x12p\n" +
	"\x11CreateDirectMount\x12,.arca.filesystem.v1.CreateDirectMountRequest\x1a-.arca.filesystem.v1.CreateDirectMountResponse\x12p\n" +
	"\x11GenerateHostsFile\x12,.arca.filesystem.v1.GenerateHostsFileRequest\x1a-.arca.filesystem.v1.GenerateHostsFileResponseB7Z5github.com/vas-solutus/arca-services/proto/filesystemb\x06proto3"

var (
	file_filesystem_proto_rawDescOnce sync.Once
	file_filesystem_proto_rawDescData []byte
)

func file_filesystem_proto_rawDescGZIP() []byte {
	file_filesystem_proto_rawDescOnce.Do(func() {
		file_filesystem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_filesystem_proto_rawDesc), len(file_filesystem_proto_rawDesc)))
	})
	return file_filesystem_proto_rawDescData
}

var file_filesystem_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_filesystem_proto_goTypes = []any{
	(*ReadyRequest)(nil),                // 0: arca.filesystem.v1.ReadyRequest
	(*ReadyResponse)(nil),               // 1: arca.filesystem.v1.ReadyResponse
	(*SyncFilesystemRequest)(nil),       // 2: arca.filesystem.v1.SyncFilesystemRequest
	(*SyncFilesystemResponse)(nil),      // 3: arca.filesystem.v1.SyncFilesystemResponse
	(*EnumerateUpperdirRequest)(nil),    // 4: arca.filesystem.v1.EnumerateUpperdirRequest
	(*EnumerateUpperdirResponse)(nil),   // 5: arca.filesystem.v1.EnumerateUpperdirResponse
	(*UpperdirEntry)(nil),               // 6: arca.filesystem.v1.UpperdirEntry
	(*ReadArchiveRequest)(nil),          // 7: arca.filesystem.v1.ReadArchiveRequest
	(*ReadArchiveResponse)(nil),         // 8: arca.filesystem.v1.ReadArchiveResponse
	(*PathStat)(nil),                    // 9: arca.filesystem.v1.PathStat
	(*WriteArchiveRequest)(nil),         // 10: arca.filesystem.v1.WriteArchiveRequest
	(*WriteArchiveResponse)(nil),        // 11: arca.filesystem.v1.WriteArchiveResponse
	(*CreateBindMountRequest)(nil),      // 12: arca.filesystem.v1.CreateBindMountRequest
	(*CreateBindMountResponse)(nil),     // 13: arca.filesystem.v1.CreateBindMountResponse
	(*StatPathRequest)(nil),             // 14: arca.filesystem.v1.StatPathRequest
	(*StatPathResponse)(nil),            // 15: arca.filesystem.v1.StatPathResponse
	(*CreateVolumeOverlayRequest)(nil),  // 16: arca.filesystem.v1.CreateVolumeOverlayRequest
	(*CreateVolumeOverlayResponse)(nil), // 17: arca.filesystem.v1.CreateVolumeOverlayResponse
	(*CreateDirectMountRequest)(nil),    // 18: arca.filesystem.v1.CreateDirectMountRequest
	(*CreateDirectMountResponse)(nil),   // 19: arca.filesystem.v1.CreateDirectMountResponse
	(*GenerateHostsFileRequest)(nil),    // 20: arca.filesystem.v1.GenerateHostsFileRequest
	(*GenerateHostsFileResponse)(nil),   // 21: arca.filesystem.v1.GenerateHostsFileResponse
}
var file_filesystem_proto_depIdxs = []int32{
	6,  // 0: arca.filesystem.v1.EnumerateUpperdirResponse.entries:type_name -> arca.filesystem.v1.UpperdirEntry
	9,  // 1: arca.filesystem.v1.ReadArchiveResponse.stat:type_name -> arca.filesystem.v1.PathStat
	9,  // 2: arca.filesystem.v1.StatPathResponse.stat:type_name -> arca.filesystem.v1.PathStat
	0,  // 3: arca.filesystem.v1.FilesystemService.Ready:input_type -> arca.filesystem.v1.ReadyRequest
	2,  // 4: arca.filesystem.v1.FilesystemService.SyncFilesystem:input_type -> arca.filesystem.v1.SyncFilesystemRequest
	4,  // 5: arca.filesystem.v1.FilesystemService.EnumerateUpperdir:input_type -> arca.filesystem.v1.EnumerateUpperdirRequest
	7,  // 6: arca.filesystem.v1.FilesystemService.ReadArchive:input_type -> arca.filesystem.v1.ReadArchiveRequest
	10, // 7: arca.filesystem.v1.FilesystemService.WriteArchive:input_type -> arca.filesystem.v1.WriteArchiveRequest
	12, // 8: arca.filesystem.v1.FilesystemService.CreateBindMount:input_type -> arca.filesystem.v1.CreateBindMountRequest
	14, // 9: arca.filesystem.v1.FilesystemService.StatPath:input_type -> arca.filesystem.v1.StatPathRequest
	16, // 10: arca.filesystem.v1.FilesystemService.CreateVolumeOverlay:input_type -> arca.filesystem.v1.CreateVolumeOverlayRequest
	18, // 11: arca.filesystem.v1.FilesystemService.CreateDirectMount:input_type -> arca.filesystem.v1.CreateDirectMountRequest
	20, // 12: arca.filesystem.v1.FilesystemService.GenerateHostsFile:input_type -> arca.filesystem.v1.GenerateHostsFileRequest
	1,  // 13: arca.filesystem.v1.FilesystemService.Ready:output_type -> arca.filesystem.v1.ReadyResponse
	3,  // 14: arca.filesystem.v1.FilesystemService.SyncFilesystem:output_type -> arca.filesystem.v1.SyncFilesystemResponse
	5,  // 15: arca.filesystem.v1.FilesystemService.EnumerateUpperdir:output_type -> arca.filesystem.v1.EnumerateUpperdirResponse
	8,  // 16: arca.filesystem.v1.FilesystemService.ReadArchive:output_type -> arca.filesystem.v1.ReadArchiveResponse
	11, // 17: arca.filesystem.v1.FilesystemService.WriteArchive:output_type -> arca.filesystem.v1.WriteArchiveResponse
	13, // 18: arca.filesystem.v1.FilesystemService.CreateBindMount:output_type -> arca.filesystem.v1.CreateBindMountResponse
	15, // 19: arca.filesystem.v1.FilesystemService.StatPath:output_type -> arca.filesystem.v1.StatPathResponse
	17, // 20: arca.filesystem.v1.FilesystemService.CreateVolumeOverlay:output_type -> arca.filesystem.v1.CreateVolumeOverlayResponse
	19, // 21: arca.filesystem.v1.FilesystemService.CreateDirectMount:output_type -> arca.filesystem.v1.CreateDirectMountResponse
	21, // 22: arca.filesystem.v1.FilesystemService.GenerateHostsFile:output_type -> arca.filesystem.v1.GenerateHostsFileResponse
	13, // [13:23] is the sub-list for method output_type
	3,  // [3:13] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_filesystem_proto_init() }
func file_filesystem_proto_init() {
	if File_filesystem_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_filesystem_proto_rawDesc), len(file_filesystem_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_filesystem_proto_goTypes,
		DependencyIndexes: file_filesystem_proto_depIdxs,
		MessageInfos:      file_filesystem_proto_msgTypes,
	}.Build()
	File_filesystem_proto = out.File
	file_filesystem_proto_goTypes = nil
	file_filesystem_proto_depIdxs = nil
}
